-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.actividad_plataforma_semanal
(
    id_actividad serial NOT NULL,
    id_cuenta integer NOT NULL,
    anio integer NOT NULL,
    semana integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    problemas_resueltos integer DEFAULT 0,
    intentos_totales integer DEFAULT 0,
    tiempo_total_minutos integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT actividad_plataforma_semanal_pkey PRIMARY KEY (id_actividad),
    CONSTRAINT actividad_plataforma_semanal_id_cuenta_anio_semana_key UNIQUE (id_cuenta, anio, semana)
);

CREATE TABLE IF NOT EXISTS public.catalogo_alcance_evento
(
    id_alcance serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    orden integer,
    CONSTRAINT catalogo_alcance_evento_pkey PRIMARY KEY (id_alcance),
    CONSTRAINT catalogo_alcance_evento_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.catalogo_carrera
(
    id_carrera serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    codigo character varying(20) COLLATE pg_catalog."default",
    activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT catalogo_carrera_pkey PRIMARY KEY (id_carrera),
    CONSTRAINT catalogo_carrera_codigo_key UNIQUE (codigo),
    CONSTRAINT catalogo_carrera_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.catalogo_plataforma
(
    id_plataforma serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    url_base character varying(255) COLLATE pg_catalog."default",
    requiere_usuario boolean DEFAULT true,
    activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT catalogo_plataforma_pkey PRIMARY KEY (id_plataforma),
    CONSTRAINT catalogo_plataforma_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.catalogo_rol_staff
(
    id_rol serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    puede_administrar boolean DEFAULT false,
    puede_editar boolean DEFAULT false,
    puede_ver boolean DEFAULT true,
    CONSTRAINT catalogo_rol_staff_pkey PRIMARY KEY (id_rol),
    CONSTRAINT catalogo_rol_staff_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.catalogo_tipo_evento
(
    id_tipo_evento serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    requiere_costo boolean DEFAULT false,
    permite_equipos boolean DEFAULT false,
    activo boolean DEFAULT true,
    CONSTRAINT catalogo_tipo_evento_pkey PRIMARY KEY (id_tipo_evento),
    CONSTRAINT catalogo_tipo_evento_nombre_key UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS public.concurso
(
    id_concurso serial NOT NULL,
    id_evento integer NOT NULL,
    id_plataforma integer,
    modalidad character varying(20) COLLATE pg_catalog."default" NOT NULL,
    min_integrantes_equipo integer DEFAULT 1,
    max_integrantes_equipo integer,
    requiere_asesor boolean DEFAULT false,
    requiere_cuenta_especial boolean DEFAULT false,
    url_concurso character varying(500) COLLATE pg_catalog."default",
    permite_registro_tardio boolean DEFAULT false,
    fecha_limite_registro timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT concurso_pkey PRIMARY KEY (id_concurso),
    CONSTRAINT concurso_id_evento_key UNIQUE (id_evento)
);

COMMENT ON TABLE public.concurso
    IS 'Extensión de evento para concursos de programación';

CREATE TABLE IF NOT EXISTS public.cuenta_plataforma
(
    id_cuenta serial NOT NULL,
    id_miembro integer NOT NULL,
    id_plataforma integer NOT NULL,
    usuario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    problemas_resueltos_total integer DEFAULT 0,
    problemas_resueltos_semana integer DEFAULT 0,
    problema_mas_dificil character varying(100) COLLATE pg_catalog."default",
    ranking integer,
    rating integer,
    ultima_actualizacion timestamp without time zone,
    activo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cuenta_plataforma_pkey PRIMARY KEY (id_cuenta),
    CONSTRAINT cuenta_plataforma_id_miembro_id_plataforma_key UNIQUE (id_miembro, id_plataforma),
    CONSTRAINT cuenta_plataforma_id_plataforma_usuario_key UNIQUE (id_plataforma, usuario)
);

CREATE TABLE IF NOT EXISTS public.equipo_concurso
(
    id_equipo serial NOT NULL,
    id_concurso integer NOT NULL,
    nombre_equipo character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nombre_asesor character varying(255) COLLATE pg_catalog."default",
    correo_asesor character varying(255) COLLATE pg_catalog."default",
    telefono_asesor character varying(20) COLLATE pg_catalog."default",
    institucion_asesor character varying(255) COLLATE pg_catalog."default",
    usuario_acceso character varying(100) COLLATE pg_catalog."default",
    contrasena_acceso character varying(255) COLLATE pg_catalog."default",
    registro_completo boolean DEFAULT false,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    confirmado boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT equipo_concurso_pkey PRIMARY KEY (id_equipo),
    CONSTRAINT equipo_concurso_id_concurso_nombre_equipo_key UNIQUE (id_concurso, nombre_equipo)
);

COMMENT ON TABLE public.equipo_concurso
    IS 'Equipos participantes en concursos por equipos';

CREATE TABLE IF NOT EXISTS public.evento
(
    id_evento serial NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion_html text COLLATE pg_catalog."default",
    id_tipo_evento integer NOT NULL,
    id_alcance integer NOT NULL,
    fecha_inicio date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    fecha_fin date NOT NULL,
    hora_fin time without time zone NOT NULL,
    ubicacion character varying(255) COLLATE pg_catalog."default",
    cupos integer,
    cupos_disponibles integer,
    tiene_costo boolean DEFAULT false,
    costo numeric(10, 2) DEFAULT 0.00,
    imagen_flyer_url character varying(500) COLLATE pg_catalog."default",
    imagen_flyer_key character varying(255) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'planificacion'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT evento_pkey PRIMARY KEY (id_evento)
);

CREATE TABLE IF NOT EXISTS public.evidencia
(
    id_evidencia serial NOT NULL,
    id_evento integer NOT NULL,
    titulo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    tipo character varying(20) COLLATE pg_catalog."default",
    url character varying(500) COLLATE pg_catalog."default",
    storage_key character varying(255) COLLATE pg_catalog."default",
    tamanio_bytes integer,
    mime_type character varying(100) COLLATE pg_catalog."default",
    fecha_captura timestamp without time zone,
    orden integer DEFAULT 0,
    publica boolean DEFAULT true,
    id_miembro_creador integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT evidencia_pkey PRIMARY KEY (id_evidencia)
);

COMMENT ON TABLE public.evidencia
    IS 'Evidencias multimedia de eventos para línea de tiempo';

COMMENT ON COLUMN public.evidencia.orden
    IS 'Orden de aparición en la línea de tiempo del evento';

CREATE TABLE IF NOT EXISTS public.inscripcion_evento
(
    id_inscripcion serial NOT NULL,
    id_evento integer NOT NULL,
    id_miembro integer,
    id_invitado integer,
    id_equipo integer,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'pendiente'::character varying,
    requiere_pago boolean DEFAULT false,
    pago_completado boolean DEFAULT false,
    asistio boolean DEFAULT false,
    hora_registro_asistencia timestamp without time zone,
    fecha_inscripcion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inscripcion_evento_pkey PRIMARY KEY (id_inscripcion),
    CONSTRAINT inscripcion_evento_id_evento_id_invitado_key UNIQUE (id_evento, id_invitado),
    CONSTRAINT inscripcion_evento_id_evento_id_miembro_key UNIQUE (id_evento, id_miembro),
    CONSTRAINT un_tipo_inscrito CHECK (
        (id_miembro IS NOT NULL)::integer + 
        (id_invitado IS NOT NULL)::integer + 
        (id_equipo IS NOT NULL)::integer = 1
    )
);

COMMENT ON TABLE public.inscripcion_evento
    IS 'Registro unificado de inscripciones para miembros e invitados';

COMMENT ON COLUMN public.inscripcion_evento.requiere_pago
    IS 'Se determina automáticamente según evento.tiene_costo';

CREATE TABLE IF NOT EXISTS public.integrante_equipo
(
    id_integrante serial NOT NULL,
    id_equipo integer NOT NULL,
    id_miembro integer,
    id_invitado integer,
    es_capitan boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT integrante_equipo_pkey PRIMARY KEY (id_integrante)
);

CREATE TABLE IF NOT EXISTS public.invitado
(
    id_invitado serial NOT NULL,
    nombre_completo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    correo_electronico character varying(255) COLLATE pg_catalog."default" NOT NULL,
    numero_telefono character varying(20) COLLATE pg_catalog."default",
    nivel_estudios character varying(50) COLLATE pg_catalog."default",
    semestre integer,
    carrera character varying(100) COLLATE pg_catalog."default",
    escuela_institucion character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT invitado_pkey PRIMARY KEY (id_invitado),
    CONSTRAINT invitado_correo_electronico_key UNIQUE (correo_electronico)
);

CREATE TABLE IF NOT EXISTS public.miembro
(
    id_miembro serial NOT NULL,
    nombre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido_paterno character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido_materno character varying(100) COLLATE pg_catalog."default",
    correo_electronico character varying(255) COLLATE pg_catalog."default" NOT NULL,
    numero_telefono character varying(20) COLLATE pg_catalog."default",
    id_carrera integer,
    semestre_ingreso integer NOT NULL,
    semestre_actual integer NOT NULL,
    periodo_ingreso character varying(20) COLLATE pg_catalog."default" NOT NULL,
    es_club_programacion boolean DEFAULT false,
    es_computer_society boolean DEFAULT false,
    numero_ieee character varying(50) COLLATE pg_catalog."default",
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'activo'::character varying,
    contrasena character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    rol character varying(20) COLLATE pg_catalog."default" DEFAULT 'usuario'::character varying,
    CONSTRAINT miembro_pkey PRIMARY KEY (id_miembro),
    CONSTRAINT miembro_correo_electronico_key UNIQUE (correo_electronico),
    CONSTRAINT miembro_numero_ieee_key UNIQUE (numero_ieee)
);

COMMENT ON TABLE public.miembro
    IS 'Miembros del club de programación y/o Computer Society';

COMMENT ON COLUMN public.miembro.semestre_actual
    IS 'Se actualiza automáticamente cada inicio de semestre';

COMMENT ON COLUMN public.miembro.periodo_ingreso
    IS 'Define cuándo incrementar el semestre: enero o agosto';

COMMENT ON COLUMN public.miembro.numero_ieee
    IS 'Requerido solo si es_computer_society = true';

CREATE TABLE IF NOT EXISTS public.pago
(
    id_pago serial NOT NULL,
    id_inscripcion integer NOT NULL,
    monto numeric(10, 2) NOT NULL,
    moneda character varying(3) COLLATE pg_catalog."default" DEFAULT 'MXN'::character varying,
    mp_preference_id character varying(255) COLLATE pg_catalog."default",
    mp_payment_id character varying(255) COLLATE pg_catalog."default",
    mp_status character varying(50) COLLATE pg_catalog."default",
    mp_status_detail character varying(100) COLLATE pg_catalog."default",
    mp_response_json jsonb,
    estado character varying(20) COLLATE pg_catalog."default" DEFAULT 'pendiente'::character varying,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_pago timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pago_pkey PRIMARY KEY (id_pago),
    CONSTRAINT pago_id_inscripcion_key UNIQUE (id_inscripcion)
);

COMMENT ON TABLE public.pago
    IS 'Gestión de pagos integrada con Mercado Pago';

COMMENT ON COLUMN public.pago.mp_response_json
    IS 'Almacena la respuesta completa de Mercado Pago para auditoría';

CREATE TABLE IF NOT EXISTS public.participacion_concurso_individual
(
    id_participacion serial NOT NULL,
    id_concurso integer NOT NULL,
    id_miembro integer,
    id_invitado integer,
    posicion integer,
    puntos_obtenidos numeric(10, 2),
    problemas_resueltos integer,
    tiempo_total_minutos integer,
    confirmado boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT participacion_concurso_individual_pkey PRIMARY KEY (id_participacion),
    CONSTRAINT participacion_concurso_individual_id_concurso_id_invitado_key UNIQUE (id_concurso, id_invitado),
    CONSTRAINT participacion_concurso_individual_id_concurso_id_miembro_key UNIQUE (id_concurso, id_miembro)
);

CREATE TABLE IF NOT EXISTS public.password_reset_token
(
    id_token serial NOT NULL,
    id_miembro integer NOT NULL,
    token character varying(255) COLLATE pg_catalog."default" NOT NULL,
    codigo_verificacion character varying(6) COLLATE pg_catalog."default",
    expires_at timestamp without time zone NOT NULL,
    usado boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    used_at timestamp without time zone,
    CONSTRAINT password_reset_token_pkey PRIMARY KEY (id_token),
    CONSTRAINT password_reset_token_token_key UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public.resultado_equipo_concurso
(
    id_resultado serial NOT NULL,
    id_equipo integer NOT NULL,
    posicion integer,
    puntos_obtenidos numeric(10, 2),
    problemas_resueltos integer,
    tiempo_total_minutos integer,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT resultado_equipo_concurso_pkey PRIMARY KEY (id_resultado),
    CONSTRAINT resultado_equipo_concurso_id_equipo_key UNIQUE (id_equipo)
);

CREATE TABLE IF NOT EXISTS public.staff_evento
(
    id_staff serial NOT NULL,
    id_evento integer NOT NULL,
    id_miembro integer NOT NULL,
    id_rol integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT staff_evento_pkey PRIMARY KEY (id_staff),
    CONSTRAINT staff_evento_id_evento_id_miembro_key UNIQUE (id_evento, id_miembro)
);

ALTER TABLE IF EXISTS public.actividad_plataforma_semanal
    ADD CONSTRAINT actividad_plataforma_semanal_id_cuenta_fkey FOREIGN KEY (id_cuenta)
    REFERENCES public.cuenta_plataforma (id_cuenta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_actividad_cuenta
    ON public.actividad_plataforma_semanal(id_cuenta);


ALTER TABLE IF EXISTS public.concurso
    ADD CONSTRAINT concurso_id_evento_fkey FOREIGN KEY (id_evento)
    REFERENCES public.evento (id_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_concurso_evento
    ON public.concurso(id_evento);


ALTER TABLE IF EXISTS public.concurso
    ADD CONSTRAINT concurso_id_plataforma_fkey FOREIGN KEY (id_plataforma)
    REFERENCES public.catalogo_plataforma (id_plataforma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_concurso_plataforma
    ON public.concurso(id_plataforma);


ALTER TABLE IF EXISTS public.cuenta_plataforma
    ADD CONSTRAINT cuenta_plataforma_id_miembro_fkey FOREIGN KEY (id_miembro)
    REFERENCES public.miembro (id_miembro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_cuenta_miembro
    ON public.cuenta_plataforma(id_miembro);


ALTER TABLE IF EXISTS public.cuenta_plataforma
    ADD CONSTRAINT cuenta_plataforma_id_plataforma_fkey FOREIGN KEY (id_plataforma)
    REFERENCES public.catalogo_plataforma (id_plataforma) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_cuenta_plataforma
    ON public.cuenta_plataforma(id_plataforma);


ALTER TABLE IF EXISTS public.equipo_concurso
    ADD CONSTRAINT equipo_concurso_id_concurso_fkey FOREIGN KEY (id_concurso)
    REFERENCES public.concurso (id_concurso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_equipo_concurso
    ON public.equipo_concurso(id_concurso);


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_id_alcance_fkey FOREIGN KEY (id_alcance)
    REFERENCES public.catalogo_alcance_evento (id_alcance) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_evento_alcance
    ON public.evento(id_alcance);


ALTER TABLE IF EXISTS public.evento
    ADD CONSTRAINT evento_id_tipo_evento_fkey FOREIGN KEY (id_tipo_evento)
    REFERENCES public.catalogo_tipo_evento (id_tipo_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_evento_tipo
    ON public.evento(id_tipo_evento);


ALTER TABLE IF EXISTS public.evidencia
    ADD CONSTRAINT evidencia_id_evento_fkey FOREIGN KEY (id_evento)
    REFERENCES public.evento (id_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_evidencia_evento
    ON public.evidencia(id_evento);


ALTER TABLE IF EXISTS public.evidencia
    ADD CONSTRAINT evidencia_id_miembro_creador_fkey FOREIGN KEY (id_miembro_creador)
    REFERENCES public.miembro (id_miembro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inscripcion_evento
    ADD CONSTRAINT inscripcion_evento_id_equipo_fkey FOREIGN KEY (id_equipo)
    REFERENCES public.equipo_concurso (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.inscripcion_evento
    ADD CONSTRAINT inscripcion_evento_id_evento_fkey FOREIGN KEY (id_evento)
    REFERENCES public.evento (id_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_inscripcion_evento
    ON public.inscripcion_evento(id_evento);


ALTER TABLE IF EXISTS public.inscripcion_evento
    ADD CONSTRAINT inscripcion_evento_id_invitado_fkey FOREIGN KEY (id_invitado)
    REFERENCES public.invitado (id_invitado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_inscripcion_invitado
    ON public.inscripcion_evento(id_invitado);


ALTER TABLE IF EXISTS public.inscripcion_evento
    ADD CONSTRAINT inscripcion_evento_id_miembro_fkey FOREIGN KEY (id_miembro)
    REFERENCES public.miembro (id_miembro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_inscripcion_miembro
    ON public.inscripcion_evento(id_miembro);


ALTER TABLE IF EXISTS public.integrante_equipo
    ADD CONSTRAINT integrante_equipo_id_equipo_fkey FOREIGN KEY (id_equipo)
    REFERENCES public.equipo_concurso (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_integrante_equipo
    ON public.integrante_equipo(id_equipo);


ALTER TABLE IF EXISTS public.integrante_equipo
    ADD CONSTRAINT integrante_equipo_id_invitado_fkey FOREIGN KEY (id_invitado)
    REFERENCES public.invitado (id_invitado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.integrante_equipo
    ADD CONSTRAINT integrante_equipo_id_miembro_fkey FOREIGN KEY (id_miembro)
    REFERENCES public.miembro (id_miembro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.miembro
    ADD CONSTRAINT miembro_id_carrera_fkey FOREIGN KEY (id_carrera)
    REFERENCES public.catalogo_carrera (id_carrera) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_miembro_carrera
    ON public.miembro(id_carrera);


ALTER TABLE IF EXISTS public.pago
    ADD CONSTRAINT pago_id_inscripcion_fkey FOREIGN KEY (id_inscripcion)
    REFERENCES public.inscripcion_evento (id_inscripcion) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pago_inscripcion
    ON public.pago(id_inscripcion);


ALTER TABLE IF EXISTS public.participacion_concurso_individual
    ADD CONSTRAINT participacion_concurso_individual_id_concurso_fkey FOREIGN KEY (id_concurso)
    REFERENCES public.concurso (id_concurso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.participacion_concurso_individual
    ADD CONSTRAINT participacion_concurso_individual_id_invitado_fkey FOREIGN KEY (id_invitado)
    REFERENCES public.invitado (id_invitado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.participacion_concurso_individual
    ADD CONSTRAINT participacion_concurso_individual_id_miembro_fkey FOREIGN KEY (id_miembro)
    REFERENCES public.miembro (id_miembro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.password_reset_token
    ADD CONSTRAINT password_reset_token_id_miembro_fkey FOREIGN KEY (id_miembro)
    REFERENCES public.miembro (id_miembro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.resultado_equipo_concurso
    ADD CONSTRAINT resultado_equipo_concurso_id_equipo_fkey FOREIGN KEY (id_equipo)
    REFERENCES public.equipo_concurso (id_equipo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS resultado_equipo_concurso_id_equipo_key
    ON public.resultado_equipo_concurso(id_equipo);


ALTER TABLE IF EXISTS public.staff_evento
    ADD CONSTRAINT staff_evento_id_evento_fkey FOREIGN KEY (id_evento)
    REFERENCES public.evento (id_evento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_staff_evento
    ON public.staff_evento(id_evento);


ALTER TABLE IF EXISTS public.staff_evento
    ADD CONSTRAINT staff_evento_id_miembro_fkey FOREIGN KEY (id_miembro)
    REFERENCES public.miembro (id_miembro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_staff_miembro
    ON public.staff_evento(id_miembro);


ALTER TABLE IF EXISTS public.staff_evento
    ADD CONSTRAINT staff_evento_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES public.catalogo_rol_staff (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

-- SEED DATA -------------------------------------------------------------

-- Carreras
INSERT INTO catalogo_carrera (nombre, codigo) VALUES 
('Ingeniería en Sistemas Computacionales', 'ISC'),
('Ingeniería en Electronica', 'IEL'),
('Ingeniería Industrial', 'II'),
('Ingeniería Quimica', 'IQ'),
('Ingeniería en Logistica', 'IL'),
('Ingeniería en Mecatronica', 'IM')
ON CONFLICT (codigo) DO NOTHING;

-- Tipos Evento
INSERT INTO catalogo_tipo_evento (nombre) VALUES 
('Concurso'), ('Hackathon'), ('Conferencia'), ('Taller'), ('Rifa'), ('Reunión')
ON CONFLICT (nombre) DO NOTHING;

-- Alcance Evento
INSERT INTO catalogo_alcance_evento (nombre) VALUES 
('Abierto'), ('Estudiantes Tecnológico'), ('Miembros Club'), ('Miembros Capitulo')
ON CONFLICT (nombre) DO NOTHING;

-- Plataformas
INSERT INTO catalogo_plataforma (nombre) VALUES 
('Codeforces'), ('OmegaUp'), ('VJudge')
ON CONFLICT (nombre) DO NOTHING;

-- Roles Staff
INSERT INTO catalogo_rol_staff (nombre) VALUES 
('Administrador'), ('Logistica'), ('Juez'), ('Apoyo')
ON CONFLICT (nombre) DO NOTHING;

END;